### ISSUE TITLE
希望提供 all in docker 的安装方式

### ISSUE THREAD

**Issue by 543069760** [hapydev-team/hapydev#2]
希望提供 all in docker 的安装方式，另外建议文档注明最低的 npm 以及 node 版本

目前测试 14、18 版本 好像都有 vite 的问题，另外建的 server 安装模块 vite 配置文件增加 host 字段，开启0.0.0.0 监听，而不仅仅是 location

**Comment by hapydevlab** [comment]
已全面支持Docker 方式快速安装
https://github.com/hapydev-team/hapydev/releases/tag/v0.1.2
