### ISSUE TITLE
目前 npm 安装 hapydev 始终报错

### ISSUE THREAD

**Issue by 543069760** [hapydev-team/hapydev#3]
Dockerfile ：
# 使用官方的滚动更新 Ubuntu 镜像作为基础镜像
FROM ubuntu:rolling

# 安装必要的软件包，包括 Node.js v20.18.1 和 npm
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 确保我们安装的是 Node.js v20.18.1
RUN npm install -g n && \
    n 20.18.1 && \
    npm config set prefix /usr/local

# 设置工作目录
WORKDIR /app

# 将当前路径下的所有文件（此步骤已经提前 GIT 到当前 hapydev 目录下）直接全部复制到容器内的 /app 目录
COPY . .

# 安装指定版本的 react 和 react-dom
RUN npm install react@18.3.1 react-dom@18.3.1

# 全局安装 tsx 和 vite
RUN npm install -g tsx vite

# 安装所有依赖，包括开发依赖
RUN npm install --legacy-peer-deps

# 显式安装 @vitejs/plugin-react 以确保它被包含在项目依赖中
RUN npm install --save-dev @vitejs/plugin-react

# 暴露应用程序运行的端口
EXPOSE 8000

# 启动命令保持不变
CMD ["npm", "start"]

**报错如下（目前看更换 20.x 版本 18.x 版本 均与react 报错有关，看package.json 指定版本是react@"18.3.1" ：

但是又提示peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3  不知道哪个不兼容哪个，始终运行不起来**

> [6/9] RUN npm install react@18.3.1 react-dom@18.3.1:
#0 39.06 npm error code ERESOLVE
#0 39.07 npm error ERESOLVE unable to resolve dependency tree
#0 39.07 npm error
#0 39.07 npm error While resolving: hapydev@1.0.0
#0 39.07 npm error Found: react@18.3.1
#0 39.07 npm error node_modules/react
#0 39.07 npm error   react@"18.3.1" from the root project
#0 39.07 npm error
#0 39.07 npm error Could not resolve dependency:
#0 39.07 npm error peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
#0 39.07 npm error node_modules/react-json-view
#0 39.07 npm error   react-json-view@"^1.21.3" from the root project
#0 39.07 npm error
#0 39.07 npm error Fix the upstream dependency conflict, or retry
#0 39.07 npm error this command with --force or --legacy-peer-deps
#0 39.07 npm error to accept an incorrect (and potentially broken) dependency resolution.
#0 39.07 npm error
#0 39.07 npm error
#0 39.07 npm error For a full report see:
#0 39.07 npm error /root/.npm/_logs/2024-12-12T19_41_48_898Z-eresolve-report.txt
#0 39.08 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-12T19_41_48_898Z-debug-0.log
------
Dockerfile:24
--------------------
  22 |     
  23 |     # 安装指定版本的 react 和 react-dom
  24 | >>> RUN npm install react@18.3.1 react-dom@18.3.1
  25 |     
  26 |     # 全局安装 tsx 和 vite
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install react@18.3.1 react-dom@18.3.1" did not complete successfully: exit code: 1

**Comment by 543069760** [comment]
补充hapydev（改用Node 22.12.0版本依然提示 peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3）：

#0 29.77 npm error code ERESOLVE                                                                                                                                                                                                 
#0 29.77 npm error ERESOLVE unable to resolve dependency tree                                                                                                                                                                    
#0 29.77 npm error                                                                                                                                                                                                               
#0 29.77 npm error While resolving: hapydev@1.0.0                                                                                                                                                                                
#0 29.77 npm error Found: react@18.3.1
#0 29.77 npm error node_modules/react
#0 29.77 npm error   react@"^18.3.1" from the root project
#0 29.77 npm error
#0 29.77 npm error Could not resolve dependency:
#0 29.77 npm error peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
#0 29.77 npm error node_modules/react-json-view
#0 29.77 npm error   react-json-view@"^1.21.3" from the root project
#0 29.77 npm error
#0 29.77 npm error Fix the upstream dependency conflict, or retry
#0 29.77 npm error this command with --force or --legacy-peer-deps
#0 29.77 npm error to accept an incorrect (and potentially broken) dependency resolution.
#0 29.77 npm error
#0 29.77 npm error
#0 29.77 npm error For a full report see:
#0 29.77 npm error /root/.npm/_logs/2024-12-13T09_20_27_417Z-eresolve-report.txt
#0 29.78 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-13T09_20_27_417Z-debug-0.log

**Comment by hapydevlab** [comment]
报错跟第三方组件react-json-view有关，已换成其他组件

**Comment by 543069760** [comment]
> 报错跟第三方组件react-json-view有关，已换成其他组件

感谢官方回复，是不是重新git clone 重新npm install ?

**Comment by hapydevlab** [comment]
已在v0.1.1版修复
