### ISSUE TITLE
菜单接口管理下有个+号，点击接口导入无任何反应

### ISSUE THREAD

**Issue by lewis-ing** [hapydev-team/hapydev#4]
1、菜单接口管理下有个+号，点击接口导入无任何反应
2、接口管理是否可以添加一个为该项目的全局baseUrl,方便进行测试
3、是否有全局token进行管理

**Comment by hapydevlab** [comment]
已在v0.1.1版修复

**Comment by hapydevlab** [comment]
已在v0.1.1版修复
