### ISSUE TITLE
Docker版本 URL引用有问题

### ISSUE THREAD

**Issue by 543069760** [hapydev-team/hapydev#5]
Docker版本 URL引用有问题

Docker版本运行起来之后，端口映射的方式

URL还是引用了 localhost 这个地址（正常hapydev前端代码不应该是这个地址而是 Docker容器的映射的地址），导致部分文件 加载异常，以及无法送调用请求

**浏览器报错如下**：

`socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF56pOE net::ERR_CONNECTION_REFUSED
[新] 通过在 Microsoft Edge 中使用 Copilot 来解释控制台错误: 在上面 
 以说明错误。 了解更多信息
不再显示
index-Y3qeCOyw.js:25 
 
 GET http://localhost/assets/tree-sitter.wasm net::ERR_CONNECTION_REFUSED
index-Y3qeCOyw.js:25 
 
 Uncaught (in promise) TypeError: Failed to fetch
    at createWasm (index-Y3qeCOyw.js:25:17663)
    at index-Y3qeCOyw.js:25:35795
    at new Promise (<anonymous>)
    at Parser.init (index-Y3qeCOyw.js:25:9388)
    at setConfig (index-Y3qeCOyw.js:25:80874)
    at index-Y3qeCOyw.js:25:139212
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF56qHi net::ERR_CONNECTION_REFUSED
angle-left-Kk3NGc0i.js:1 
 
 GET http://localhost/scripts/monaco-editor/min/vs/loader.js net::ERR_CONNECTION_REFUSED
:8003/project/7be343…9041-19b43764c425:1 
 Uncaught (in promise) 
Event {isTrusted: true, type: 'error', target: script, currentTarget: null, eventPhase: 0, …}
:8003/project/7be343…9041-19b43764c425:1 
 Uncaught (in promise) 
Event {isTrusted: true, type: 'error', target: script, currentTarget: null, eventPhase: 0, …}
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF56rNL net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF56sjM net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF56v-H net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF5704r net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF5788Z net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF57GC6 net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF57O5l net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF57V_T net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF57e7R net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF57mB2 net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF57uEo net::ERR_CONNECTION_REFUSED
socket.io.4.4.1.min.js:827 
 
 GET http://localhost:6003/socket.io/?EIO=4&transport=polling&t=PF580IT net::ERR_CONNECTION_REFUSED`

**Comment by 543069760** [comment]
解决方式，修改项目 .env配置文件为自己环境的IP，重新Vite build部署

**Comment by hapydevlab** [comment]
通过Docker方式部署，可以通过传入CLOUD_PROXY_URL变量，设置为socket代理真实地址
  支持动态传入环境变量如下

  |  变量名称   | 变量描述  |  变量示例值   |
  |  ----  | ----  |  ----  |
  | BASE_URL  | Web应用实际ip地址 | 'http://127.0.0.1:8000'  |
  | CLOUD_PROXY_URL  | 云端代理地址 | 'http://127.0.0.1:6003'  |
  | API_HOST_URL  | api服务地址 | 'http://127.0.0.1:6002/api/v1.0'  |
  | DOC_HOST_URL  | 文档访问地址 | 'http://127.0.0.1:6004'  |
