### ISSUE TITLE
接口请求接口的返回结果，在返回的body的美化和原生下一直在加载中

### ISSUE THREAD

**Issue by lewis-ing** [hapydev-team/hapydev#6]
1、使用请求接口：https://petstore3.swagger.io/api/v3/pet/findByStatus?status=available
2、请求成功了，在响应的返回结果中，一直无法显示结果，代码都是最新的

![image](https://github.com/user-attachments/assets/17e24d5e-5c19-4e78-8105-8ed0a0603879)

**Comment by hapydevlab** [comment]
如果是使用开发模式运行的话，请修改根目录下
.env.development文件，VITE_BASE_URL='http://127.0.0.1:8000'这里改成实际的ip地址
如果是Docker方式运行，设置BASE_URL变量为实际的ip地址

**Comment by lewis-ing** [comment]
源码开发模式也不行

**Comment by hapydevlab** [comment]
如需帮助，请加客服微信
<img width="160" src="https://github.com/hapydev-team/hapydev/raw/main/src/assets/products/contact-wechat.png" />

**Comment by hapydevlab** [comment]
可以修改.env.development文件
```
#hapydev官网地址
VITE_HOME_URL="https://www.hapydev.com"

#Web应用实际ip地址
VITE_BASE_URL='http://127.0.0.1:8000'


#云端代理地址
VITE_CLOUD_PROXY_URL="http://127.0.0.1:6003"

#api服务地址
VITE_API_URL="http://127.0.0.1:6002/api/v1.0"

#头像资源地址
VITE_ASSETS_URL='/files'

#单次下载接口个数
VITE_DOWNLOAD_BUFFER_SIZE=5

# 文档访问地址
VITE_DOC_HOST="http://127.0.0.1:6004/docs"

# 文档页公网域名
VITE_FIRST_DOMAIN=".you-host.com"
```
修改VITE_BASE_URL参数

如果您的app访问地址为http://192.168.0.1:8000/project/xxxxx ，VITE_BASE_URL就改成 http://192.168.0.1:8000

如果您的app访问地址为http://localhost/project/xxxx ，VITE_BASE_URL就改成 http://localhost

如果您的问题还未解决，请扫下方微信

<img src="https://github.com/user-attachments/assets/3227bcbe-b87e-46a0-8733-c38a4b6e5fd1" width="160" />

**Comment by lewis-ing** [comment]
按照以上方式，已解决
